DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

DROP TABLE IF EXISTS useradmin;
CREATE TABLE useradmin (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

DROP TABLE IF EXISTS job;
CREATE TABLE job (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company TEXT,
  job TEXT,
  domain TEXT,
  salary TEXT
);

DROP TABLE IF EXISTS jobapplied;
CREATE TABLE jobapplied (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	uid INTEGER,
	jid INTEGER
);
